@lbPort=5000

### Taret List
GET http://localhost:{{lbPort}}/manage/target


### Insert target
POST http://localhost:{{lbPort}}/manage/target
content-type: application/json

{
  "host": "localhost",
  "port": "4001" 
}

### Insert target
POST http://localhost:{{lbPort}}/manage/target
content-type: application/json

{
  "host": "localhost",
  "port": "4002" 
}

### Insert target
POST http://localhost:{{lbPort}}/manage/target
content-type: application/json

{
  "host": "localhost",
  "port": "4003" 
}

### Insert target
POST http://localhost:{{lbPort}}/manage/target
content-type: application/json

{
  "host": "localhost",
  "port": "4004" 
}

### Delete target
DELETE http://localhost:{{lbPort}}/manage/target
content-type: application/json

{
  "host": "localhost",
  "port": "4000" 
}